/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashinternal;


import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author ellan
 */
public class dashboardpage extends javax.swing.JInternalFrame {

    /**
     * Creates new form dashboardpage
     */
    public dashboardpage() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bif = (BasicInternalFrameUI)this.getUI();
        bif.setNorthPane(null);
    }
    
        Color enter  = new Color(136,8,8);
        Color exit = new Color(74,4,4);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addreservation = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        seatplacement = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dateandtime = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dashboardpagepane = new javax.swing.JDesktopPane();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(74, 4, 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addreservation.setBackground(new java.awt.Color(74, 4, 4));
        addreservation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(240, 240, 240), new java.awt.Color(240, 240, 240), new java.awt.Color(240, 240, 240), new java.awt.Color(240, 240, 240)));
        addreservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addreservationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addreservationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addreservationMouseExited(evt);
            }
        });
        addreservation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add Reservation");
        addreservation.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 11, 150, 30));

        jPanel1.add(addreservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 50));

        seatplacement.setBackground(new java.awt.Color(74, 4, 4));
        seatplacement.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(240, 240, 240), new java.awt.Color(240, 240, 240), new java.awt.Color(240, 240, 240), new java.awt.Color(240, 240, 240)));
        seatplacement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seatplacementMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seatplacementMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                seatplacementMouseExited(evt);
            }
        });
        seatplacement.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Seat Placement");
        seatplacement.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 11, 170, 28));

        jPanel1.add(seatplacement, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 250, 50));

        dateandtime.setBackground(new java.awt.Color(74, 4, 4));
        dateandtime.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(240, 240, 240), new java.awt.Color(240, 240, 240), new java.awt.Color(240, 240, 240), new java.awt.Color(240, 240, 240)));
        dateandtime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateandtimeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dateandtimeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dateandtimeMouseExited(evt);
            }
        });
        dateandtime.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Date and Time");
        dateandtime.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 11, 160, 28));

        jPanel1.add(dateandtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 250, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 50));

        dashboardpagepane.setBackground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout dashboardpagepaneLayout = new javax.swing.GroupLayout(dashboardpagepane);
        dashboardpagepane.setLayout(dashboardpagepaneLayout);
        dashboardpagepaneLayout.setHorizontalGroup(
            dashboardpagepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        dashboardpagepaneLayout.setVerticalGroup(
            dashboardpagepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(dashboardpagepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 750, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addreservationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addreservationMouseEntered
        addreservation.setBackground(enter);
    }//GEN-LAST:event_addreservationMouseEntered

    private void addreservationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addreservationMouseExited
        addreservation.setBackground(exit);
    }//GEN-LAST:event_addreservationMouseExited

    private void seatplacementMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seatplacementMouseEntered
        seatplacement.setBackground(enter);
    }//GEN-LAST:event_seatplacementMouseEntered

    private void seatplacementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seatplacementMouseExited
        seatplacement.setBackground(exit);
    }//GEN-LAST:event_seatplacementMouseExited

    private void dateandtimeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateandtimeMouseEntered
        dateandtime.setBackground(enter);
    }//GEN-LAST:event_dateandtimeMouseEntered

    private void dateandtimeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateandtimeMouseExited
        dateandtime.setBackground(exit);
    }//GEN-LAST:event_dateandtimeMouseExited

    private void addreservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addreservationMouseClicked
  
    }//GEN-LAST:event_addreservationMouseClicked

    private void seatplacementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seatplacementMouseClicked
       
    }//GEN-LAST:event_seatplacementMouseClicked

    private void dateandtimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateandtimeMouseClicked
     
    }//GEN-LAST:event_dateandtimeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addreservation;
    private javax.swing.JDesktopPane dashboardpagepane;
    private javax.swing.JPanel dateandtime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel seatplacement;
    // End of variables declaration//GEN-END:variables
}
